name: release-docs
on:
  push:
    branches: [ test-workflow ]
jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install software
        run: |
          sudo apt-get install python3-sphinx
          sudo pip install furo==2022.4.7
          sudo pip install myst-parser==0.17.2
          sudo pip install sphinx-copybutton==0.5.0
          sudo pip install sphinx-design==0.1.0
          sudo pip install sphinx-inline-tabs==2022.1.2b11
      - name: make html
        run: |
          ls
          make html